# syntax=docker/dockerfile:1

ARG NODE_VERSION=20.13.1

FROM node:${NODE_VERSION}-alpine

# Use development node environment by default.
ENV NODE_ENV development



WORKDIR /usr/src/app

#Change the owner of the /usr/src/app directory to the non-root user.
# RUN chown -R node:node /usr/src/app

COPY package.json ./

COPY .env.dev .env 


RUN npm install


# Run the application as a non-root user.
# USER node

# Copy the rest of the source files into the image.
COPY . .

# Expose the port that the application listens on.
EXPOSE 3400

# Run the application.
CMD ["npm", "run", "dev"]
